-- Esquema completo de tablas de rides/riders (exportado del estado actual de producción)
-- Estas tablas ya existen en Supabase; esta migración documenta el esquema para control de versiones.

CREATE TABLE IF NOT EXISTS app_version (
  id integer NOT NULL DEFAULT 1,
  version text NOT NULL DEFAULT '0.1.0'::text,
  apk_url text,
  release_notes text,
  force_update boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT app_version_pkey PRIMARY KEY (id),
  CONSTRAINT app_version_single_row CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS riders (
  id uuid NOT NULL PRIMARY KEY,
  nombre text NOT NULL,
  apellido text,
  ciudad text,
  correo text,
  telefono text,
  edad integer,
  moto_marca text,
  moto_modelo text,
  moto_cc integer,
  tipo_moto text,
  placa text,
  foto_url text,
  foto_mapa text,
  viaja text,
  slug text,
  soat_vence date,
  tecno_vence date,
  ultima_notif_soat date,
  ultima_notif_tecno date,
  ultima_notif_tip timestamptz,
  km_actual integer,
  notif_activa boolean DEFAULT true,
  aniversario_moto date,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rides (
  id text NOT NULL PRIMARY KEY,
  nombre text,
  lider_id uuid NOT NULL,
  estado text NOT NULL DEFAULT 'activa'::text,
  planned_route jsonb,
  planned_steps jsonb,
  origin_name text,
  destination_name text,
  origin_lat double precision,
  origin_lon double precision,
  destination_lat double precision,
  destination_lon double precision,
  planned_distance_km double precision,
  planned_duration_min integer,
  drive_folder_url text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS members (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ride_id text NOT NULL REFERENCES rides(id),
  uid uuid NOT NULL,
  rol text NOT NULL DEFAULT 'rider'::text,
  nombre text,
  lat double precision,
  lon double precision,
  speed_kmh double precision DEFAULT 0,
  last_seen timestamptz DEFAULT now(),
  joined_at timestamptz DEFAULT now(),
  status_code integer NOT NULL DEFAULT 0,
  emergency_name text,
  emergency_phone text,
  distance_km double precision,
  duration_seconds integer,
  max_speed_kmh double precision,
  video_url text,
  finished_at timestamptz,
  notes text,
  hidden boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS route_points (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ride_id text NOT NULL REFERENCES rides(id),
  uid uuid NOT NULL,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  speed_kmh double precision DEFAULT 0,
  recorded_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ride_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ride_id text NOT NULL REFERENCES rides(id),
  uid uuid NOT NULL,
  url text NOT NULL,
  lat double precision,
  lon double precision,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rider_push_tokens (
  uid uuid NOT NULL PRIMARY KEY,
  onesignal_id text NOT NULL,
  platform text DEFAULT 'android'::text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS video_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  ride_id text NOT NULL,
  state text NOT NULL DEFAULT 'queued'::text,
  progress integer NOT NULL DEFAULT 0,
  url text,
  error text,
  worker_id text,
  input_data jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz
);

-- RLS ya está activado en todas estas tablas en producción
-- Las políticas de seguridad están configuradas correctamente
